// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/tiles/v1/tiles.proto (package civil.public.tiles.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file civil/public/tiles/v1/tiles.proto.
 */
export declare const file_civil_public_tiles_v1_tiles: GenFile;

/**
 * @generated from message civil.public.tiles.v1.GetParcelTilesRequest
 */
export declare type GetParcelTilesRequest = Message<"civil.public.tiles.v1.GetParcelTilesRequest"> & {
  /**
   * @generated from field: int32 z = 1;
   */
  z: number;

  /**
   * @generated from field: int32 x = 2;
   */
  x: number;

  /**
   * @generated from field: int32 y = 3;
   */
  y: number;
};

/**
 * Describes the message civil.public.tiles.v1.GetParcelTilesRequest.
 * Use `create(GetParcelTilesRequestSchema)` to create a new message.
 */
export declare const GetParcelTilesRequestSchema: GenMessage<GetParcelTilesRequest>;

/**
 * @generated from message civil.public.tiles.v1.GetParcelTilesResponse
 */
export declare type GetParcelTilesResponse = Message<"civil.public.tiles.v1.GetParcelTilesResponse"> & {
  /**
   * @generated from field: string content_type = 1;
   */
  contentType: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message civil.public.tiles.v1.GetParcelTilesResponse.
 * Use `create(GetParcelTilesResponseSchema)` to create a new message.
 */
export declare const GetParcelTilesResponseSchema: GenMessage<GetParcelTilesResponse>;

/**
 * @generated from service civil.public.tiles.v1.TileService
 */
export declare const TileService: GenService<{
  /**
   * @generated from rpc civil.public.tiles.v1.TileService.GetParcelTiles
   */
  getParcelTiles: {
    methodKind: "unary";
    input: typeof GetParcelTilesRequestSchema;
    output: typeof GetParcelTilesResponseSchema;
  },
}>;

