// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/tiles/v1/tiles.proto (package civil.public.tiles.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file civil/public/tiles/v1/tiles.proto.
 */
export declare const file_civil_public_tiles_v1_tiles: GenFile;

/**
 * @generated from message civil.public.tiles.v1.GetTileJsonRequest
 */
export declare type GetTileJsonRequest = Message<"civil.public.tiles.v1.GetTileJsonRequest"> & {
  /**
   * e.g., "parcels"
   *
   * @generated from field: string source_name = 1;
   */
  sourceName: string;
};

/**
 * Describes the message civil.public.tiles.v1.GetTileJsonRequest.
 * Use `create(GetTileJsonRequestSchema)` to create a new message.
 */
export declare const GetTileJsonRequestSchema: GenMessage<GetTileJsonRequest>;

/**
 * TileJsonResponse represents the standard TileJSON (v2.2.0/v3.0.0) spec.
 *
 * @generated from message civil.public.tiles.v1.GetTileJsonResponse
 */
export declare type GetTileJsonResponse = Message<"civil.public.tiles.v1.GetTileJsonResponse"> & {
  /**
   * Usually "2.2.0" or "3.0.0"
   *
   * @generated from field: string tilejson = 1;
   */
  tilejson: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * The URL array for tiles
   *
   * @generated from field: repeated string tiles = 4;
   */
  tiles: string[];

  /**
   * @generated from field: int32 minzoom = 5;
   */
  minzoom: number;

  /**
   * @generated from field: int32 maxzoom = 6;
   */
  maxzoom: number;

  /**
   * @generated from field: repeated double bounds = 7;
   */
  bounds: number[];

  /**
   * @generated from field: repeated double center = 8;
   */
  center: number[];

  /**
   * vector_layers is critical for Mapbox Vector Tiles (MVT)
   *
   * @generated from field: repeated civil.public.tiles.v1.VectorLayer vector_layers = 9;
   */
  vectorLayers: VectorLayer[];
};

/**
 * Describes the message civil.public.tiles.v1.GetTileJsonResponse.
 * Use `create(GetTileJsonResponseSchema)` to create a new message.
 */
export declare const GetTileJsonResponseSchema: GenMessage<GetTileJsonResponse>;

/**
 * @generated from message civil.public.tiles.v1.VectorLayer
 */
export declare type VectorLayer = Message<"civil.public.tiles.v1.VectorLayer"> & {
  /**
   * The name of the table/layer
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: int32 minzoom = 3;
   */
  minzoom: number;

  /**
   * @generated from field: int32 maxzoom = 4;
   */
  maxzoom: number;

  /**
   * Metadata about the columns
   *
   * @generated from field: map<string, string> fields = 5;
   */
  fields: { [key: string]: string };
};

/**
 * Describes the message civil.public.tiles.v1.VectorLayer.
 * Use `create(VectorLayerSchema)` to create a new message.
 */
export declare const VectorLayerSchema: GenMessage<VectorLayer>;

/**
 * @generated from message civil.public.tiles.v1.GetTileRequest
 */
export declare type GetTileRequest = Message<"civil.public.tiles.v1.GetTileRequest"> & {
  /**
   * @generated from field: string source_name = 1;
   */
  sourceName: string;

  /**
   * @generated from field: int32 z = 2;
   */
  z: number;

  /**
   * @generated from field: int32 x = 3;
   */
  x: number;

  /**
   * @generated from field: int32 y = 4;
   */
  y: number;
};

/**
 * Describes the message civil.public.tiles.v1.GetTileRequest.
 * Use `create(GetTileRequestSchema)` to create a new message.
 */
export declare const GetTileRequestSchema: GenMessage<GetTileRequest>;

/**
 * @generated from message civil.public.tiles.v1.GetTileResponse
 */
export declare type GetTileResponse = Message<"civil.public.tiles.v1.GetTileResponse"> & {
  /**
   * @generated from field: string content_type = 1;
   */
  contentType: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message civil.public.tiles.v1.GetTileResponse.
 * Use `create(GetTileResponseSchema)` to create a new message.
 */
export declare const GetTileResponseSchema: GenMessage<GetTileResponse>;

/**
 * @generated from service civil.public.tiles.v1.TileService
 */
export declare const TileService: GenService<{
  /**
   * GetTileJson retrieves the discovery metadata for a tile source.
   * Clients use this to configure map layers.
   *
   * @generated from rpc civil.public.tiles.v1.TileService.GetTileJson
   */
  getTileJson: {
    methodKind: "unary";
    input: typeof GetTileJsonRequestSchema;
    output: typeof GetTileJsonResponseSchema;
  },
  /**
   * GetTile retrieves a vector tile (MVT/PBF) for a given coordinate.
   *
   * @generated from rpc civil.public.tiles.v1.TileService.GetTile
   */
  getTile: {
    methodKind: "unary";
    input: typeof GetTileRequestSchema;
    output: typeof GetTileResponseSchema;
  },
}>;

