// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/landuses/v1/land_uses.proto (package civil.public.landuses.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file civil/public/landuses/v1/land_uses.proto.
 */
export declare const file_civil_public_landuses_v1_land_uses: GenFile;

/**
 * @generated from message civil.public.landuses.v1.LandUse
 */
export declare type LandUse = Message<"civil.public.landuses.v1.LandUse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string code = 3;
   */
  code: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: string land_use_type_id = 5;
   */
  landUseTypeId: string;

  /**
   * @generated from field: string land_use_type_name = 6;
   */
  landUseTypeName: string;
};

/**
 * Describes the message civil.public.landuses.v1.LandUse.
 * Use `create(LandUseSchema)` to create a new message.
 */
export declare const LandUseSchema: GenMessage<LandUse>;

/**
 * @generated from message civil.public.landuses.v1.GetLandUsesRequest
 */
export declare type GetLandUsesRequest = Message<"civil.public.landuses.v1.GetLandUsesRequest"> & {
};

/**
 * Describes the message civil.public.landuses.v1.GetLandUsesRequest.
 * Use `create(GetLandUsesRequestSchema)` to create a new message.
 */
export declare const GetLandUsesRequestSchema: GenMessage<GetLandUsesRequest>;

/**
 * @generated from message civil.public.landuses.v1.GetLandUsesResponse
 */
export declare type GetLandUsesResponse = Message<"civil.public.landuses.v1.GetLandUsesResponse"> & {
  /**
   * @generated from field: map<string, civil.public.landuses.v1.LandUse> land_uses = 1;
   */
  landUses: { [key: string]: LandUse };
};

/**
 * Describes the message civil.public.landuses.v1.GetLandUsesResponse.
 * Use `create(GetLandUsesResponseSchema)` to create a new message.
 */
export declare const GetLandUsesResponseSchema: GenMessage<GetLandUsesResponse>;

/**
 * @generated from message civil.public.landuses.v1.LandUseType
 */
export declare type LandUseType = Message<"civil.public.landuses.v1.LandUseType"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string code = 3;
   */
  code: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;
};

/**
 * Describes the message civil.public.landuses.v1.LandUseType.
 * Use `create(LandUseTypeSchema)` to create a new message.
 */
export declare const LandUseTypeSchema: GenMessage<LandUseType>;

/**
 * @generated from message civil.public.landuses.v1.GetLandUseTypesRequest
 */
export declare type GetLandUseTypesRequest = Message<"civil.public.landuses.v1.GetLandUseTypesRequest"> & {
};

/**
 * Describes the message civil.public.landuses.v1.GetLandUseTypesRequest.
 * Use `create(GetLandUseTypesRequestSchema)` to create a new message.
 */
export declare const GetLandUseTypesRequestSchema: GenMessage<GetLandUseTypesRequest>;

/**
 * @generated from message civil.public.landuses.v1.GetLandUseTypesResponse
 */
export declare type GetLandUseTypesResponse = Message<"civil.public.landuses.v1.GetLandUseTypesResponse"> & {
  /**
   * @generated from field: map<string, civil.public.landuses.v1.LandUseType> land_use_types = 1;
   */
  landUseTypes: { [key: string]: LandUseType };
};

/**
 * Describes the message civil.public.landuses.v1.GetLandUseTypesResponse.
 * Use `create(GetLandUseTypesResponseSchema)` to create a new message.
 */
export declare const GetLandUseTypesResponseSchema: GenMessage<GetLandUseTypesResponse>;

/**
 * @generated from service civil.public.landuses.v1.LandUsesService
 */
export declare const LandUsesService: GenService<{
  /**
   * @generated from rpc civil.public.landuses.v1.LandUsesService.GetLandUses
   */
  getLandUses: {
    methodKind: "unary";
    input: typeof GetLandUsesRequestSchema;
    output: typeof GetLandUsesResponseSchema;
  },
  /**
   * @generated from rpc civil.public.landuses.v1.LandUsesService.GetLandUseTypes
   */
  getLandUseTypes: {
    methodKind: "unary";
    input: typeof GetLandUseTypesRequestSchema;
    output: typeof GetLandUseTypesResponseSchema;
  },
}>;

