// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/valuations/v1/valuations.proto (package civil.public.valuations.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file civil/public/valuations/v1/valuations.proto.
 */
export declare const file_civil_public_valuations_v1_valuations: GenFile;

/**
 * @generated from message civil.public.valuations.v1.Valuation
 */
export declare type Valuation = Message<"civil.public.valuations.v1.Valuation"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp valuation_timestamp = 2;
   */
  valuationTimestamp?: Timestamp;
};

/**
 * Describes the message civil.public.valuations.v1.Valuation.
 * Use `create(ValuationSchema)` to create a new message.
 */
export declare const ValuationSchema: GenMessage<Valuation>;

/**
 * @generated from message civil.public.valuations.v1.GetValuationsRequest
 */
export declare type GetValuationsRequest = Message<"civil.public.valuations.v1.GetValuationsRequest"> & {
};

/**
 * Describes the message civil.public.valuations.v1.GetValuationsRequest.
 * Use `create(GetValuationsRequestSchema)` to create a new message.
 */
export declare const GetValuationsRequestSchema: GenMessage<GetValuationsRequest>;

/**
 * @generated from message civil.public.valuations.v1.GetValuationsResponse
 */
export declare type GetValuationsResponse = Message<"civil.public.valuations.v1.GetValuationsResponse"> & {
  /**
   * @generated from field: map<string, civil.public.valuations.v1.Valuation> valuations = 1;
   */
  valuations: { [key: string]: Valuation };
};

/**
 * Describes the message civil.public.valuations.v1.GetValuationsResponse.
 * Use `create(GetValuationsResponseSchema)` to create a new message.
 */
export declare const GetValuationsResponseSchema: GenMessage<GetValuationsResponse>;

/**
 * @generated from service civil.public.valuations.v1.ValuationService
 */
export declare const ValuationService: GenService<{
  /**
   * @generated from rpc civil.public.valuations.v1.ValuationService.GetValuations
   */
  getValuations: {
    methodKind: "unary";
    input: typeof GetValuationsRequestSchema;
    output: typeof GetValuationsResponseSchema;
  },
}>;

