// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/dex/v1/dex.proto (package civil.public.dex.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file civil/public/dex/v1/dex.proto.
 */
export declare const file_civil_public_dex_v1_dex: GenFile;

/**
 * @generated from message civil.public.dex.v1.Client
 */
export declare type Client = Message<"civil.public.dex.v1.Client"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string secret = 2;
   */
  secret: string;

  /**
   * @generated from field: repeated string redirect_uris = 3;
   */
  redirectUris: string[];

  /**
   * @generated from field: repeated string trusted_peers = 4;
   */
  trustedPeers: string[];

  /**
   * @generated from field: bool public = 5;
   */
  public: boolean;

  /**
   * @generated from field: string name = 6;
   */
  name: string;

  /**
   * @generated from field: string logo_url = 7;
   */
  logoUrl: string;

  /**
   * @generated from field: repeated string allowed_connectors = 8;
   */
  allowedConnectors: string[];

  /**
   * @generated from field: repeated string sso_shared_with = 9;
   */
  ssoSharedWith: string[];
};

/**
 * Describes the message civil.public.dex.v1.Client.
 * Use `create(ClientSchema)` to create a new message.
 */
export declare const ClientSchema: GenMessage<Client>;

/**
 * ClientInfo represents an OAuth2 client without sensitive information.
 *
 * @generated from message civil.public.dex.v1.ClientInfo
 */
export declare type ClientInfo = Message<"civil.public.dex.v1.ClientInfo"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: repeated string redirect_uris = 2;
   */
  redirectUris: string[];

  /**
   * @generated from field: repeated string trusted_peers = 3;
   */
  trustedPeers: string[];

  /**
   * @generated from field: bool public = 4;
   */
  public: boolean;

  /**
   * @generated from field: string name = 5;
   */
  name: string;

  /**
   * @generated from field: string logo_url = 6;
   */
  logoUrl: string;

  /**
   * @generated from field: repeated string allowed_connectors = 7;
   */
  allowedConnectors: string[];

  /**
   * @generated from field: repeated string sso_shared_with = 8;
   */
  ssoSharedWith: string[];
};

/**
 * Describes the message civil.public.dex.v1.ClientInfo.
 * Use `create(ClientInfoSchema)` to create a new message.
 */
export declare const ClientInfoSchema: GenMessage<ClientInfo>;

/**
 * GetClientReq is a request to retrieve client details.
 *
 * @generated from message civil.public.dex.v1.GetClientRequest
 */
export declare type GetClientRequest = Message<"civil.public.dex.v1.GetClientRequest"> & {
  /**
   * The ID of the client.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message civil.public.dex.v1.GetClientRequest.
 * Use `create(GetClientRequestSchema)` to create a new message.
 */
export declare const GetClientRequestSchema: GenMessage<GetClientRequest>;

/**
 * GetClientResp returns the client details.
 *
 * @generated from message civil.public.dex.v1.GetClientResponse
 */
export declare type GetClientResponse = Message<"civil.public.dex.v1.GetClientResponse"> & {
  /**
   * @generated from field: civil.public.dex.v1.Client client = 1;
   */
  client?: Client;
};

/**
 * Describes the message civil.public.dex.v1.GetClientResponse.
 * Use `create(GetClientResponseSchema)` to create a new message.
 */
export declare const GetClientResponseSchema: GenMessage<GetClientResponse>;

/**
 * CreateClientReq is a request to make a client.
 *
 * @generated from message civil.public.dex.v1.CreateClientRequest
 */
export declare type CreateClientRequest = Message<"civil.public.dex.v1.CreateClientRequest"> & {
  /**
   * @generated from field: civil.public.dex.v1.Client client = 1;
   */
  client?: Client;
};

/**
 * Describes the message civil.public.dex.v1.CreateClientRequest.
 * Use `create(CreateClientRequestSchema)` to create a new message.
 */
export declare const CreateClientRequestSchema: GenMessage<CreateClientRequest>;

/**
 * CreateClientResp returns the response from creating a client.
 *
 * @generated from message civil.public.dex.v1.CreateClientResponse
 */
export declare type CreateClientResponse = Message<"civil.public.dex.v1.CreateClientResponse"> & {
  /**
   * @generated from field: bool already_exists = 1;
   */
  alreadyExists: boolean;

  /**
   * @generated from field: civil.public.dex.v1.Client client = 2;
   */
  client?: Client;
};

/**
 * Describes the message civil.public.dex.v1.CreateClientResponse.
 * Use `create(CreateClientResponseSchema)` to create a new message.
 */
export declare const CreateClientResponseSchema: GenMessage<CreateClientResponse>;

/**
 * DeleteClientReq is a request to delete a client.
 *
 * @generated from message civil.public.dex.v1.DeleteClientRequest
 */
export declare type DeleteClientRequest = Message<"civil.public.dex.v1.DeleteClientRequest"> & {
  /**
   * The ID of the client.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message civil.public.dex.v1.DeleteClientRequest.
 * Use `create(DeleteClientRequestSchema)` to create a new message.
 */
export declare const DeleteClientRequestSchema: GenMessage<DeleteClientRequest>;

/**
 * DeleteClientResp determines if the client is deleted successfully.
 *
 * @generated from message civil.public.dex.v1.DeleteClientResponse
 */
export declare type DeleteClientResponse = Message<"civil.public.dex.v1.DeleteClientResponse"> & {
  /**
   * @generated from field: bool not_found = 1;
   */
  notFound: boolean;
};

/**
 * Describes the message civil.public.dex.v1.DeleteClientResponse.
 * Use `create(DeleteClientResponseSchema)` to create a new message.
 */
export declare const DeleteClientResponseSchema: GenMessage<DeleteClientResponse>;

/**
 * UpdateClientReq is a request to update an existing client.
 *
 * @generated from message civil.public.dex.v1.UpdateClientRequest
 */
export declare type UpdateClientRequest = Message<"civil.public.dex.v1.UpdateClientRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: repeated string redirect_uris = 2;
   */
  redirectUris: string[];

  /**
   * @generated from field: repeated string trusted_peers = 3;
   */
  trustedPeers: string[];

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: string logo_url = 5;
   */
  logoUrl: string;

  /**
   * @generated from field: repeated string allowed_connectors = 6;
   */
  allowedConnectors: string[];

  /**
   * @generated from field: repeated string sso_shared_with = 7;
   */
  ssoSharedWith: string[];
};

/**
 * Describes the message civil.public.dex.v1.UpdateClientRequest.
 * Use `create(UpdateClientRequestSchema)` to create a new message.
 */
export declare const UpdateClientRequestSchema: GenMessage<UpdateClientRequest>;

/**
 * UpdateClientResp returns the response from updating a client.
 *
 * @generated from message civil.public.dex.v1.UpdateClientResponse
 */
export declare type UpdateClientResponse = Message<"civil.public.dex.v1.UpdateClientResponse"> & {
  /**
   * @generated from field: bool not_found = 1;
   */
  notFound: boolean;
};

/**
 * Describes the message civil.public.dex.v1.UpdateClientResponse.
 * Use `create(UpdateClientResponseSchema)` to create a new message.
 */
export declare const UpdateClientResponseSchema: GenMessage<UpdateClientResponse>;

/**
 * ListClientReq is a request to enumerate clients.
 *
 * @generated from message civil.public.dex.v1.ListClientsRequest
 */
export declare type ListClientsRequest = Message<"civil.public.dex.v1.ListClientsRequest"> & {
};

/**
 * Describes the message civil.public.dex.v1.ListClientsRequest.
 * Use `create(ListClientsRequestSchema)` to create a new message.
 */
export declare const ListClientsRequestSchema: GenMessage<ListClientsRequest>;

/**
 * ListClientResp returns a list of clients.
 *
 * @generated from message civil.public.dex.v1.ListClientsResponse
 */
export declare type ListClientsResponse = Message<"civil.public.dex.v1.ListClientsResponse"> & {
  /**
   * @generated from field: repeated civil.public.dex.v1.ClientInfo clients = 1;
   */
  clients: ClientInfo[];
};

/**
 * Describes the message civil.public.dex.v1.ListClientsResponse.
 * Use `create(ListClientsResponseSchema)` to create a new message.
 */
export declare const ListClientsResponseSchema: GenMessage<ListClientsResponse>;

/**
 * VersionReq is a request to fetch version info.
 *
 * @generated from message civil.public.dex.v1.GetVersionRequest
 */
export declare type GetVersionRequest = Message<"civil.public.dex.v1.GetVersionRequest"> & {
};

/**
 * Describes the message civil.public.dex.v1.GetVersionRequest.
 * Use `create(GetVersionRequestSchema)` to create a new message.
 */
export declare const GetVersionRequestSchema: GenMessage<GetVersionRequest>;

/**
 * VersionResp holds the version info of components.
 *
 * @generated from message civil.public.dex.v1.GetVersionResponse
 */
export declare type GetVersionResponse = Message<"civil.public.dex.v1.GetVersionResponse"> & {
  /**
   * Semantic version of the server.
   *
   * @generated from field: string server = 1;
   */
  server: string;

  /**
   * Numeric version of the API. It increases every time a new call is added to the API.
   * Clients should use this info to determine if the server supports specific features.
   *
   * @generated from field: int32 api = 2;
   */
  api: number;
};

/**
 * Describes the message civil.public.dex.v1.GetVersionResponse.
 * Use `create(GetVersionResponseSchema)` to create a new message.
 */
export declare const GetVersionResponseSchema: GenMessage<GetVersionResponse>;

/**
 * RefreshTokenRef contains the metadata for a refresh token that is managed by the storage.
 *
 * @generated from message civil.public.dex.v1.RefreshTokenRef
 */
export declare type RefreshTokenRef = Message<"civil.public.dex.v1.RefreshTokenRef"> & {
  /**
   * ID of the refresh token.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * @generated from field: int64 created_at = 5;
   */
  createdAt: bigint;

  /**
   * @generated from field: int64 last_used = 6;
   */
  lastUsed: bigint;
};

/**
 * Describes the message civil.public.dex.v1.RefreshTokenRef.
 * Use `create(RefreshTokenRefSchema)` to create a new message.
 */
export declare const RefreshTokenRefSchema: GenMessage<RefreshTokenRef>;

/**
 * ListRefreshReq is a request to enumerate the refresh tokens of a user.
 *
 * @generated from message civil.public.dex.v1.ListRefreshRequest
 */
export declare type ListRefreshRequest = Message<"civil.public.dex.v1.ListRefreshRequest"> & {
  /**
   * The "sub" claim returned in the ID Token.
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message civil.public.dex.v1.ListRefreshRequest.
 * Use `create(ListRefreshRequestSchema)` to create a new message.
 */
export declare const ListRefreshRequestSchema: GenMessage<ListRefreshRequest>;

/**
 * ListRefreshResp returns a list of refresh tokens for a user.
 *
 * @generated from message civil.public.dex.v1.ListRefreshResponse
 */
export declare type ListRefreshResponse = Message<"civil.public.dex.v1.ListRefreshResponse"> & {
  /**
   * @generated from field: repeated civil.public.dex.v1.RefreshTokenRef refresh_tokens = 1;
   */
  refreshTokens: RefreshTokenRef[];
};

/**
 * Describes the message civil.public.dex.v1.ListRefreshResponse.
 * Use `create(ListRefreshResponseSchema)` to create a new message.
 */
export declare const ListRefreshResponseSchema: GenMessage<ListRefreshResponse>;

/**
 * RevokeRefreshReq is a request to revoke the refresh token of the user-client pair.
 *
 * @generated from message civil.public.dex.v1.RevokeRefreshRequest
 */
export declare type RevokeRefreshRequest = Message<"civil.public.dex.v1.RevokeRefreshRequest"> & {
  /**
   * The "sub" claim returned in the ID Token.
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;
};

/**
 * Describes the message civil.public.dex.v1.RevokeRefreshRequest.
 * Use `create(RevokeRefreshRequestSchema)` to create a new message.
 */
export declare const RevokeRefreshRequestSchema: GenMessage<RevokeRefreshRequest>;

/**
 * RevokeRefreshResp determines if the refresh token is revoked successfully.
 *
 * @generated from message civil.public.dex.v1.RevokeRefreshResponse
 */
export declare type RevokeRefreshResponse = Message<"civil.public.dex.v1.RevokeRefreshResponse"> & {
  /**
   * Set to true is refresh token was not found and token could not be revoked.
   *
   * @generated from field: bool not_found = 1;
   */
  notFound: boolean;
};

/**
 * Describes the message civil.public.dex.v1.RevokeRefreshResponse.
 * Use `create(RevokeRefreshResponseSchema)` to create a new message.
 */
export declare const RevokeRefreshResponseSchema: GenMessage<RevokeRefreshResponse>;

/**
 * @generated from service civil.public.dex.v1.DexService
 */
export declare const DexService: GenService<{
  /**
   * GetClient gets a client.
   *
   * @generated from rpc civil.public.dex.v1.DexService.GetClient
   */
  getClient: {
    methodKind: "unary";
    input: typeof GetClientRequestSchema;
    output: typeof GetClientResponseSchema;
  },
  /**
   * CreateClient creates a client.
   *
   * @generated from rpc civil.public.dex.v1.DexService.CreateClient
   */
  createClient: {
    methodKind: "unary";
    input: typeof CreateClientRequestSchema;
    output: typeof CreateClientResponseSchema;
  },
  /**
   * UpdateClient updates an existing client
   *
   * @generated from rpc civil.public.dex.v1.DexService.UpdateClient
   */
  updateClient: {
    methodKind: "unary";
    input: typeof UpdateClientRequestSchema;
    output: typeof UpdateClientResponseSchema;
  },
  /**
   * DeleteClient deletes the provided client.
   *
   * @generated from rpc civil.public.dex.v1.DexService.DeleteClient
   */
  deleteClient: {
    methodKind: "unary";
    input: typeof DeleteClientRequestSchema;
    output: typeof DeleteClientResponseSchema;
  },
  /**
   * ListClients lists all client entries.
   *
   * @generated from rpc civil.public.dex.v1.DexService.ListClients
   */
  listClients: {
    methodKind: "unary";
    input: typeof ListClientsRequestSchema;
    output: typeof ListClientsResponseSchema;
  },
  /**
   * GetVersion returns version information of the server.
   *
   * @generated from rpc civil.public.dex.v1.DexService.GetVersion
   */
  getVersion: {
    methodKind: "unary";
    input: typeof GetVersionRequestSchema;
    output: typeof GetVersionResponseSchema;
  },
  /**
   * ListRefresh lists all the refresh token entries for a particular user.
   *
   * @generated from rpc civil.public.dex.v1.DexService.ListRefresh
   */
  listRefresh: {
    methodKind: "unary";
    input: typeof ListRefreshRequestSchema;
    output: typeof ListRefreshResponseSchema;
  },
  /**
   * RevokeRefresh revokes the refresh token for the provided user-client pair.
   *
   * Note that each user-client pair can have only one refresh token at a time.
   *
   * @generated from rpc civil.public.dex.v1.DexService.RevokeRefresh
   */
  revokeRefresh: {
    methodKind: "unary";
    input: typeof RevokeRefreshRequestSchema;
    output: typeof RevokeRefreshResponseSchema;
  },
}>;

