// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/zoning/v1/zoning.proto (package civil.public.zoning.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file civil/public/zoning/v1/zoning.proto.
 */
export declare const file_civil_public_zoning_v1_zoning: GenFile;

/**
 * @generated from message civil.public.zoning.v1.Zoning
 */
export declare type Zoning = Message<"civil.public.zoning.v1.Zoning"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string code = 3;
   */
  code: string;

  /**
   * @generated from field: float max_far = 4;
   */
  maxFar: number;

  /**
   * @generated from field: float min_lot_size_sq_ft = 5;
   */
  minLotSizeSqFt: number;

  /**
   * @generated from field: float max_height_ft = 6;
   */
  maxHeightFt: number;

  /**
   * @generated from field: float max_dwelling_units_per_acre = 7;
   */
  maxDwellingUnitsPerAcre: number;

  /**
   * @generated from field: float max_lot_coverage_pct = 8;
   */
  maxLotCoveragePct: number;
};

/**
 * Describes the message civil.public.zoning.v1.Zoning.
 * Use `create(ZoningSchema)` to create a new message.
 */
export declare const ZoningSchema: GenMessage<Zoning>;

/**
 * @generated from message civil.public.zoning.v1.GetZoningRequest
 */
export declare type GetZoningRequest = Message<"civil.public.zoning.v1.GetZoningRequest"> & {
};

/**
 * Describes the message civil.public.zoning.v1.GetZoningRequest.
 * Use `create(GetZoningRequestSchema)` to create a new message.
 */
export declare const GetZoningRequestSchema: GenMessage<GetZoningRequest>;

/**
 * @generated from message civil.public.zoning.v1.GetZoningResponse
 */
export declare type GetZoningResponse = Message<"civil.public.zoning.v1.GetZoningResponse"> & {
  /**
   * @generated from field: map<string, civil.public.zoning.v1.Zoning> zoning = 1;
   */
  zoning: { [key: string]: Zoning };
};

/**
 * Describes the message civil.public.zoning.v1.GetZoningResponse.
 * Use `create(GetZoningResponseSchema)` to create a new message.
 */
export declare const GetZoningResponseSchema: GenMessage<GetZoningResponse>;

/**
 * @generated from service civil.public.zoning.v1.ZoningService
 */
export declare const ZoningService: GenService<{
  /**
   * @generated from rpc civil.public.zoning.v1.ZoningService.GetZoning
   */
  getZoning: {
    methodKind: "unary";
    input: typeof GetZoningRequestSchema;
    output: typeof GetZoningResponseSchema;
  },
}>;

