// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/instance/v1/instance.proto (package civil.public.instance.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file civil/public/instance/v1/instance.proto.
 */
export declare const file_civil_public_instance_v1_instance: GenFile;

/**
 * @generated from message civil.public.instance.v1.GetInstanceMetadataRequest
 */
export declare type GetInstanceMetadataRequest = Message<"civil.public.instance.v1.GetInstanceMetadataRequest"> & {
};

/**
 * Describes the message civil.public.instance.v1.GetInstanceMetadataRequest.
 * Use `create(GetInstanceMetadataRequestSchema)` to create a new message.
 */
export declare const GetInstanceMetadataRequestSchema: GenMessage<GetInstanceMetadataRequest>;

/**
 * @generated from message civil.public.instance.v1.GetInstanceMetadataResponse
 */
export declare type GetInstanceMetadataResponse = Message<"civil.public.instance.v1.GetInstanceMetadataResponse"> & {
  /**
   * @generated from field: google.protobuf.Struct metadata = 1;
   */
  metadata?: JsonObject;
};

/**
 * Describes the message civil.public.instance.v1.GetInstanceMetadataResponse.
 * Use `create(GetInstanceMetadataResponseSchema)` to create a new message.
 */
export declare const GetInstanceMetadataResponseSchema: GenMessage<GetInstanceMetadataResponse>;

/**
 * @generated from service civil.public.instance.v1.InstanceService
 */
export declare const InstanceService: GenService<{
  /**
   * @generated from rpc civil.public.instance.v1.InstanceService.GetInstanceMetadata
   */
  getInstanceMetadata: {
    methodKind: "unary";
    input: typeof GetInstanceMetadataRequestSchema;
    output: typeof GetInstanceMetadataResponseSchema;
  },
}>;

