// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/sales/v1/sales.proto (package civil.public.sales.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { Interval } from "../../../../google/type/interval_pb";

/**
 * Describes the file civil/public/sales/v1/sales.proto.
 */
export declare const file_civil_public_sales_v1_sales: GenFile;

/**
 * @generated from message civil.public.sales.v1.Sale
 */
export declare type Sale = Message<"civil.public.sales.v1.Sale"> & {
  /**
   * @generated from field: string sale_id = 1;
   */
  saleId: string;

  /**
   * @generated from field: google.protobuf.Timestamp sale_timestamp = 2;
   */
  saleTimestamp?: Timestamp;

  /**
   * @generated from field: string sale_price = 3;
   */
  salePrice: string;

  /**
   * @generated from field: optional string seller_name = 4;
   */
  sellerName?: string;

  /**
   * @generated from field: optional string seller_address = 5;
   */
  sellerAddress?: string;

  /**
   * @generated from field: string seller_id = 6;
   */
  sellerId: string;

  /**
   * @generated from field: optional string buyer_name = 7;
   */
  buyerName?: string;

  /**
   * @generated from field: optional string buyer_address = 8;
   */
  buyerAddress?: string;

  /**
   * @generated from field: string buyer_id = 9;
   */
  buyerId: string;
};

/**
 * Describes the message civil.public.sales.v1.Sale.
 * Use `create(SaleSchema)` to create a new message.
 */
export declare const SaleSchema: GenMessage<Sale>;

/**
 * @generated from message civil.public.sales.v1.GetSalesByParcelIdRequest
 */
export declare type GetSalesByParcelIdRequest = Message<"civil.public.sales.v1.GetSalesByParcelIdRequest"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;

  /**
   * @generated from field: optional google.protobuf.Timestamp system_as_of = 3;
   */
  systemAsOf?: Timestamp;
};

/**
 * Describes the message civil.public.sales.v1.GetSalesByParcelIdRequest.
 * Use `create(GetSalesByParcelIdRequestSchema)` to create a new message.
 */
export declare const GetSalesByParcelIdRequestSchema: GenMessage<GetSalesByParcelIdRequest>;

/**
 * @generated from message civil.public.sales.v1.GetSalesByParcelIdResponse
 */
export declare type GetSalesByParcelIdResponse = Message<"civil.public.sales.v1.GetSalesByParcelIdResponse"> & {
  /**
   * @generated from field: repeated civil.public.sales.v1.Sale sales = 1;
   */
  sales: Sale[];
};

/**
 * Describes the message civil.public.sales.v1.GetSalesByParcelIdResponse.
 * Use `create(GetSalesByParcelIdResponseSchema)` to create a new message.
 */
export declare const GetSalesByParcelIdResponseSchema: GenMessage<GetSalesByParcelIdResponse>;

/**
 * @generated from message civil.public.sales.v1.GetSalesByPolygonRequest
 */
export declare type GetSalesByPolygonRequest = Message<"civil.public.sales.v1.GetSalesByPolygonRequest"> & {
  /**
   * @generated from field: string wkt_polygon = 1;
   */
  wktPolygon: string;

  /**
   * @generated from field: google.type.Interval time_range = 2;
   */
  timeRange?: Interval;

  /**
   * @generated from field: string min_sale_price = 3;
   */
  minSalePrice: string;

  /**
   * @generated from field: string max_sale_price = 4;
   */
  maxSalePrice: string;
};

/**
 * Describes the message civil.public.sales.v1.GetSalesByPolygonRequest.
 * Use `create(GetSalesByPolygonRequestSchema)` to create a new message.
 */
export declare const GetSalesByPolygonRequestSchema: GenMessage<GetSalesByPolygonRequest>;

/**
 * @generated from message civil.public.sales.v1.GetSalesByPolygonResponse
 */
export declare type GetSalesByPolygonResponse = Message<"civil.public.sales.v1.GetSalesByPolygonResponse"> & {
  /**
   * @generated from field: repeated civil.public.sales.v1.Sale sales = 1;
   */
  sales: Sale[];
};

/**
 * Describes the message civil.public.sales.v1.GetSalesByPolygonResponse.
 * Use `create(GetSalesByPolygonResponseSchema)` to create a new message.
 */
export declare const GetSalesByPolygonResponseSchema: GenMessage<GetSalesByPolygonResponse>;

/**
 * @generated from service civil.public.sales.v1.SalesService
 */
export declare const SalesService: GenService<{
  /**
   * Retrieves all of a specified parcel's attributes as an object.
   *
   * @generated from rpc civil.public.sales.v1.SalesService.GetSalesByParcelId
   */
  getSalesByParcelId: {
    methodKind: "unary";
    input: typeof GetSalesByParcelIdRequestSchema;
    output: typeof GetSalesByParcelIdResponseSchema;
  },
  /**
   * Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
   *
   * @generated from rpc civil.public.sales.v1.SalesService.GetSalesByPolygon
   */
  getSalesByPolygon: {
    methodKind: "unary";
    input: typeof GetSalesByPolygonRequestSchema;
    output: typeof GetSalesByPolygonResponseSchema;
  },
}>;

