// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/parcels/v1/parcels.proto (package civil.public.parcels.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { Interval } from "../../../../google/type/interval_pb";

/**
 * Describes the file civil/public/parcels/v1/parcels.proto.
 */
export declare const file_civil_public_parcels_v1_parcels: GenFile;

/**
 * @generated from message civil.public.parcels.v1.ParcelAffordances
 */
export declare type ParcelAffordances = Message<"civil.public.parcels.v1.ParcelAffordances"> & {
  /**
   * @generated from field: repeated string affordance_ids = 1;
   */
  affordanceIds: string[];

  /**
   * Maximum Floor Area Ratio (FAR)
   *
   * @generated from field: optional double max_far = 2;
   */
  maxFar?: number;

  /**
   * Minimum lot size in square feet
   *
   * @generated from field: optional double min_lot_size_sq_ft = 3;
   */
  minLotSizeSqFt?: number;

  /**
   * Maximum legally permitted building height in feet
   *
   * @generated from field: optional double max_height_ft = 4;
   */
  maxHeightFt?: number;

  /**
   * @generated from field: optional double max_dwelling_units_per_acre = 5;
   */
  maxDwellingUnitsPerAcre?: number;

  /**
   * @generated from field: optional double max_lot_coverage_pct = 6;
   */
  maxLotCoveragePct?: number;
};

/**
 * Describes the message civil.public.parcels.v1.ParcelAffordances.
 * Use `create(ParcelAffordancesSchema)` to create a new message.
 */
export declare const ParcelAffordancesSchema: GenMessage<ParcelAffordances>;

/**
 * @generated from message civil.public.parcels.v1.ParcelImprovementsSummary
 */
export declare type ParcelImprovementsSummary = Message<"civil.public.parcels.v1.ParcelImprovementsSummary"> & {
  /**
   * @generated from field: repeated string improvement_ids = 1;
   */
  improvementIds: string[];

  /**
   * Physically impossible to be negative
   *
   * @generated from field: double total_area_sq_ft = 2;
   */
  totalAreaSqFt: number;

  /**
   * @generated from field: int32 total_bathrooms = 3;
   */
  totalBathrooms: number;

  /**
   * @generated from field: int32 total_bedrooms = 4;
   */
  totalBedrooms: number;

  /**
   * @generated from field: int32 total_units = 5;
   */
  totalUnits: number;

  /**
   * @generated from field: optional int32 primary_year_built = 6;
   */
  primaryYearBuilt?: number;

  /**
   * @generated from field: optional string primary_condition_id = 7;
   */
  primaryConditionId?: string;

  /**
   * @generated from field: optional string total_market_improvement_value = 8;
   */
  totalMarketImprovementValue?: string;

  /**
   * @generated from field: optional string total_assessed_improvement_value = 9;
   */
  totalAssessedImprovementValue?: string;
};

/**
 * Describes the message civil.public.parcels.v1.ParcelImprovementsSummary.
 * Use `create(ParcelImprovementsSummarySchema)` to create a new message.
 */
export declare const ParcelImprovementsSummarySchema: GenMessage<ParcelImprovementsSummary>;

/**
 * @generated from message civil.public.parcels.v1.ParcelDetails
 */
export declare type ParcelDetails = Message<"civil.public.parcels.v1.ParcelDetails"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;

  /**
   * @generated from field: optional int64 feature_id = 2;
   */
  featureId?: bigint;

  /**
   * @generated from field: optional string formatted_address = 3;
   */
  formattedAddress?: string;

  /**
   * @generated from field: optional string address_id = 4;
   */
  addressId?: string;

  /**
   * @generated from field: optional string primary_owner_name = 5;
   */
  primaryOwnerName?: string;

  /**
   * @generated from field: optional string primary_owner_address = 6;
   */
  primaryOwnerAddress?: string;

  /**
   * @generated from field: repeated string party_ids = 7;
   */
  partyIds: string[];

  /**
   * @generated from field: optional string land_use_id = 8;
   */
  landUseId?: string;

  /**
   * @generated from field: optional string neighborhood_id = 9;
   */
  neighborhoodId?: string;

  /**
   * @generated from field: optional double land_area_sq_ft = 10;
   */
  landAreaSqFt?: number;

  /**
   * @generated from field: optional double frontage_ft = 11;
   */
  frontageFt?: number;

  /**
   * @generated from field: optional double depth_ft = 12;
   */
  depthFt?: number;

  /**
   * @generated from field: repeated string zoning_ids = 13;
   */
  zoningIds: string[];

  /**
   * @generated from field: optional string market_land_value = 14;
   */
  marketLandValue?: string;

  /**
   * @generated from field: optional string assessed_land_value = 15;
   */
  assessedLandValue?: string;

  /**
   * @generated from field: optional string properties = 16;
   */
  properties?: string;
};

/**
 * Describes the message civil.public.parcels.v1.ParcelDetails.
 * Use `create(ParcelDetailsSchema)` to create a new message.
 */
export declare const ParcelDetailsSchema: GenMessage<ParcelDetails>;

/**
 * @generated from message civil.public.parcels.v1.ParcelWithImprovementSummary
 */
export declare type ParcelWithImprovementSummary = Message<"civil.public.parcels.v1.ParcelWithImprovementSummary"> & {
  /**
   * @generated from field: civil.public.parcels.v1.ParcelDetails parcel_details = 1;
   */
  parcelDetails?: ParcelDetails;

  /**
   * @generated from field: civil.public.parcels.v1.ParcelImprovementsSummary improvement_summary = 2;
   */
  improvementSummary?: ParcelImprovementsSummary;
};

/**
 * Describes the message civil.public.parcels.v1.ParcelWithImprovementSummary.
 * Use `create(ParcelWithImprovementSummarySchema)` to create a new message.
 */
export declare const ParcelWithImprovementSummarySchema: GenMessage<ParcelWithImprovementSummary>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelsWithImprovementSummaryByParcelIdRequest
 */
export declare type GetParcelsWithImprovementSummaryByParcelIdRequest = Message<"civil.public.parcels.v1.GetParcelsWithImprovementSummaryByParcelIdRequest"> & {
  /**
   * @generated from field: repeated string parcel_ids = 1;
   */
  parcelIds: string[];

  /**
   * @generated from field: optional google.protobuf.Timestamp legal_as_of = 2;
   */
  legalAsOf?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp system_as_of = 3;
   */
  systemAsOf?: Timestamp;

  /**
   * @generated from field: optional string valuation_id = 4;
   */
  valuationId?: string;

  /**
   * @generated from field: optional string neighborhood_definition_id = 5;
   */
  neighborhoodDefinitionId?: string;
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelsWithImprovementSummaryByParcelIdRequest.
 * Use `create(GetParcelsWithImprovementSummaryByParcelIdRequestSchema)` to create a new message.
 */
export declare const GetParcelsWithImprovementSummaryByParcelIdRequestSchema: GenMessage<GetParcelsWithImprovementSummaryByParcelIdRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelsWithImprovementSummaryByParcelIdResponse
 */
export declare type GetParcelsWithImprovementSummaryByParcelIdResponse = Message<"civil.public.parcels.v1.GetParcelsWithImprovementSummaryByParcelIdResponse"> & {
  /**
   * @generated from field: map<string, civil.public.parcels.v1.ParcelWithImprovementSummary> parcels = 1;
   */
  parcels: { [key: string]: ParcelWithImprovementSummary };
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelsWithImprovementSummaryByParcelIdResponse.
 * Use `create(GetParcelsWithImprovementSummaryByParcelIdResponseSchema)` to create a new message.
 */
export declare const GetParcelsWithImprovementSummaryByParcelIdResponseSchema: GenMessage<GetParcelsWithImprovementSummaryByParcelIdResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelsWithImprovementSummaryByFeatureIdRequest
 */
export declare type GetParcelsWithImprovementSummaryByFeatureIdRequest = Message<"civil.public.parcels.v1.GetParcelsWithImprovementSummaryByFeatureIdRequest"> & {
  /**
   * @generated from field: repeated int64 feature_ids = 1;
   */
  featureIds: bigint[];

  /**
   * @generated from field: optional google.protobuf.Timestamp legal_as_of = 2;
   */
  legalAsOf?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp system_as_of = 3;
   */
  systemAsOf?: Timestamp;

  /**
   * @generated from field: optional string valuation_id = 4;
   */
  valuationId?: string;

  /**
   * @generated from field: optional string neighborhood_definition_id = 5;
   */
  neighborhoodDefinitionId?: string;
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelsWithImprovementSummaryByFeatureIdRequest.
 * Use `create(GetParcelsWithImprovementSummaryByFeatureIdRequestSchema)` to create a new message.
 */
export declare const GetParcelsWithImprovementSummaryByFeatureIdRequestSchema: GenMessage<GetParcelsWithImprovementSummaryByFeatureIdRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelsWithImprovementSummaryByFeatureIdResponse
 */
export declare type GetParcelsWithImprovementSummaryByFeatureIdResponse = Message<"civil.public.parcels.v1.GetParcelsWithImprovementSummaryByFeatureIdResponse"> & {
  /**
   * @generated from field: map<string, civil.public.parcels.v1.ParcelWithImprovementSummary> parcels = 1;
   */
  parcels: { [key: string]: ParcelWithImprovementSummary };
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelsWithImprovementSummaryByFeatureIdResponse.
 * Use `create(GetParcelsWithImprovementSummaryByFeatureIdResponseSchema)` to create a new message.
 */
export declare const GetParcelsWithImprovementSummaryByFeatureIdResponseSchema: GenMessage<GetParcelsWithImprovementSummaryByFeatureIdResponse>;

/**
 * @generated from message civil.public.parcels.v1.UpdateParcelRequest
 */
export declare type UpdateParcelRequest = Message<"civil.public.parcels.v1.UpdateParcelRequest"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;

  /**
   * @generated from field: optional string address_id = 2;
   */
  addressId?: string;

  /**
   * @generated from field: optional string land_use_id = 3;
   */
  landUseId?: string;

  /**
   * @generated from field: optional double land_area_sq_ft = 4;
   */
  landAreaSqFt?: number;

  /**
   * @generated from field: optional double frontage_ft = 5;
   */
  frontageFt?: number;

  /**
   * @generated from field: optional double depth_ft = 6;
   */
  depthFt?: number;

  /**
   * @generated from field: optional string properties = 7;
   */
  properties?: string;
};

/**
 * Describes the message civil.public.parcels.v1.UpdateParcelRequest.
 * Use `create(UpdateParcelRequestSchema)` to create a new message.
 */
export declare const UpdateParcelRequestSchema: GenMessage<UpdateParcelRequest>;

/**
 * @generated from message civil.public.parcels.v1.UpdateParcelResponse
 */
export declare type UpdateParcelResponse = Message<"civil.public.parcels.v1.UpdateParcelResponse"> & {
};

/**
 * Describes the message civil.public.parcels.v1.UpdateParcelResponse.
 * Use `create(UpdateParcelResponseSchema)` to create a new message.
 */
export declare const UpdateParcelResponseSchema: GenMessage<UpdateParcelResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetNumericalParcelAttributeStatsByIdRequest
 */
export declare type GetNumericalParcelAttributeStatsByIdRequest = Message<"civil.public.parcels.v1.GetNumericalParcelAttributeStatsByIdRequest"> & {
  /**
   * @generated from field: repeated string parcel_ids = 1;
   */
  parcelIds: string[];

  /**
   * @generated from field: civil.public.parcels.v1.ParcelAttribute attribute = 2;
   */
  attribute: ParcelAttribute;

  /**
   * The historical or future effective date the user wants to view.
   * If omitted, defaults to the current time.
   *
   * @generated from field: optional google.protobuf.Timestamp legal_as_of = 3;
   */
  legalAsOf?: Timestamp;

  /**
   * The time to reset the database state to
   * If omitted, defaults to the current time.
   *
   * @generated from field: optional google.protobuf.Timestamp system_as_of = 4;
   */
  systemAsOf?: Timestamp;
};

/**
 * Describes the message civil.public.parcels.v1.GetNumericalParcelAttributeStatsByIdRequest.
 * Use `create(GetNumericalParcelAttributeStatsByIdRequestSchema)` to create a new message.
 */
export declare const GetNumericalParcelAttributeStatsByIdRequestSchema: GenMessage<GetNumericalParcelAttributeStatsByIdRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetNumericalParcelAttributeStatsByIdResponse
 */
export declare type GetNumericalParcelAttributeStatsByIdResponse = Message<"civil.public.parcels.v1.GetNumericalParcelAttributeStatsByIdResponse"> & {
  /**
   * @generated from field: float mode = 1;
   */
  mode: number;

  /**
   * @generated from field: float minimum = 2;
   */
  minimum: number;

  /**
   * @generated from field: float maximum = 3;
   */
  maximum: number;

  /**
   * @generated from field: float range = 4;
   */
  range: number;

  /**
   * @generated from field: float percentile_10 = 5;
   */
  percentile10: number;

  /**
   * @generated from field: float percentile_20 = 6;
   */
  percentile20: number;

  /**
   * @generated from field: float percentile_30 = 7;
   */
  percentile30: number;

  /**
   * @generated from field: float percentile_40 = 8;
   */
  percentile40: number;

  /**
   * @generated from field: float percentile_50 = 9;
   */
  percentile50: number;

  /**
   * @generated from field: float percentile_60 = 10;
   */
  percentile60: number;

  /**
   * @generated from field: float percentile_70 = 11;
   */
  percentile70: number;

  /**
   * @generated from field: float percentile_80 = 12;
   */
  percentile80: number;

  /**
   * @generated from field: float percentile_90 = 13;
   */
  percentile90: number;

  /**
   * @generated from field: float percentile_100 = 14;
   */
  percentile100: number;

  /**
   * @generated from field: float mean = 15;
   */
  mean: number;

  /**
   * @generated from field: float standard_deviation = 16;
   */
  standardDeviation: number;

  /**
   * @generated from field: float coefficient_of_dispersion = 17;
   */
  coefficientOfDispersion: number;
};

/**
 * Describes the message civil.public.parcels.v1.GetNumericalParcelAttributeStatsByIdResponse.
 * Use `create(GetNumericalParcelAttributeStatsByIdResponseSchema)` to create a new message.
 */
export declare const GetNumericalParcelAttributeStatsByIdResponseSchema: GenMessage<GetNumericalParcelAttributeStatsByIdResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetCategoricalParcelAttributeStatsByIdRequest
 */
export declare type GetCategoricalParcelAttributeStatsByIdRequest = Message<"civil.public.parcels.v1.GetCategoricalParcelAttributeStatsByIdRequest"> & {
  /**
   * @generated from field: repeated string parcel_ids = 1;
   */
  parcelIds: string[];

  /**
   * @generated from field: civil.public.parcels.v1.ParcelAttribute attribute = 2;
   */
  attribute: ParcelAttribute;

  /**
   * The historical or future effective date the user wants to view.
   * If omitted, defaults to the current time.
   *
   * @generated from field: optional google.protobuf.Timestamp legal_as_of = 3;
   */
  legalAsOf?: Timestamp;

  /**
   * The time to reset the database state to
   * If omitted, defaults to the current time.
   *
   * @generated from field: optional google.protobuf.Timestamp system_as_of = 4;
   */
  systemAsOf?: Timestamp;
};

/**
 * Describes the message civil.public.parcels.v1.GetCategoricalParcelAttributeStatsByIdRequest.
 * Use `create(GetCategoricalParcelAttributeStatsByIdRequestSchema)` to create a new message.
 */
export declare const GetCategoricalParcelAttributeStatsByIdRequestSchema: GenMessage<GetCategoricalParcelAttributeStatsByIdRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetCategoricalParcelAttributeStatsByIdResponse
 */
export declare type GetCategoricalParcelAttributeStatsByIdResponse = Message<"civil.public.parcels.v1.GetCategoricalParcelAttributeStatsByIdResponse"> & {
  /**
   * @generated from field: string mode = 1;
   */
  mode: string;

  /**
   * @generated from field: map<string, int32> unique_values = 2;
   */
  uniqueValues: { [key: string]: number };
};

/**
 * Describes the message civil.public.parcels.v1.GetCategoricalParcelAttributeStatsByIdResponse.
 * Use `create(GetCategoricalParcelAttributeStatsByIdResponseSchema)` to create a new message.
 */
export declare const GetCategoricalParcelAttributeStatsByIdResponseSchema: GenMessage<GetCategoricalParcelAttributeStatsByIdResponse>;

/**
 * @generated from message civil.public.parcels.v1.ComparableCriteria
 */
export declare type ComparableCriteria = Message<"civil.public.parcels.v1.ComparableCriteria"> & {
  /**
   * @generated from field: civil.public.parcels.v1.ParcelAttribute attribute = 1;
   */
  attribute: ParcelAttribute;

  /**
   * @generated from field: optional double min_numerical_tolerance = 2;
   */
  minNumericalTolerance?: number;

  /**
   * @generated from field: optional double max_numerical_tolerance = 3;
   */
  maxNumericalTolerance?: number;

  /**
   * @generated from field: repeated string categorical_tolerance = 4;
   */
  categoricalTolerance: string[];
};

/**
 * Describes the message civil.public.parcels.v1.ComparableCriteria.
 * Use `create(ComparableCriteriaSchema)` to create a new message.
 */
export declare const ComparableCriteriaSchema: GenMessage<ComparableCriteria>;

/**
 * @generated from message civil.public.parcels.v1.ComparableAttribute
 */
export declare type ComparableAttribute = Message<"civil.public.parcels.v1.ComparableAttribute"> & {
  /**
   * @generated from field: civil.public.parcels.v1.ParcelAttribute attribute = 1;
   */
  attribute: ParcelAttribute;

  /**
   * @generated from field: optional double numerical_value = 2;
   */
  numericalValue?: number;

  /**
   * @generated from field: optional string categorical_value = 3;
   */
  categoricalValue?: string;
};

/**
 * Describes the message civil.public.parcels.v1.ComparableAttribute.
 * Use `create(ComparableAttributeSchema)` to create a new message.
 */
export declare const ComparableAttributeSchema: GenMessage<ComparableAttribute>;

/**
 * @generated from message civil.public.parcels.v1.EquityComparableParcel
 */
export declare type EquityComparableParcel = Message<"civil.public.parcels.v1.EquityComparableParcel"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;

  /**
   * @generated from field: int64 feature_id = 2;
   */
  featureId: bigint;

  /**
   * @generated from field: string address_id = 3;
   */
  addressId: string;

  /**
   * @generated from field: string formatted_address = 4;
   */
  formattedAddress: string;

  /**
   * @generated from field: repeated civil.public.parcels.v1.ComparableAttribute attributes = 5;
   */
  attributes: ComparableAttribute[];
};

/**
 * Describes the message civil.public.parcels.v1.EquityComparableParcel.
 * Use `create(EquityComparableParcelSchema)` to create a new message.
 */
export declare const EquityComparableParcelSchema: GenMessage<EquityComparableParcel>;

/**
 * @generated from message civil.public.parcels.v1.SaleComparableParcel
 */
export declare type SaleComparableParcel = Message<"civil.public.parcels.v1.SaleComparableParcel"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;

  /**
   * @generated from field: int64 feature_id = 2;
   */
  featureId: bigint;

  /**
   * @generated from field: string address_id = 3;
   */
  addressId: string;

  /**
   * @generated from field: string formatted_address = 4;
   */
  formattedAddress: string;

  /**
   * @generated from field: google.protobuf.Timestamp sale_time = 5;
   */
  saleTime?: Timestamp;

  /**
   * @generated from field: string sale_price = 6;
   */
  salePrice: string;

  /**
   * @generated from field: repeated civil.public.parcels.v1.ComparableAttribute attributes = 7;
   */
  attributes: ComparableAttribute[];
};

/**
 * Describes the message civil.public.parcels.v1.SaleComparableParcel.
 * Use `create(SaleComparableParcelSchema)` to create a new message.
 */
export declare const SaleComparableParcelSchema: GenMessage<SaleComparableParcel>;

/**
 * @generated from message civil.public.parcels.v1.GetEquityComparablesRequest
 */
export declare type GetEquityComparablesRequest = Message<"civil.public.parcels.v1.GetEquityComparablesRequest"> & {
  /**
   * @generated from field: string wkt_polygon = 1;
   */
  wktPolygon: string;

  /**
   * @generated from field: repeated civil.public.parcels.v1.ComparableCriteria criteria = 2;
   */
  criteria: ComparableCriteria[];

  /**
   * @generated from field: repeated string selected_parcel_ids = 3;
   */
  selectedParcelIds: string[];
};

/**
 * Describes the message civil.public.parcels.v1.GetEquityComparablesRequest.
 * Use `create(GetEquityComparablesRequestSchema)` to create a new message.
 */
export declare const GetEquityComparablesRequestSchema: GenMessage<GetEquityComparablesRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetEquityComparablesResponse
 */
export declare type GetEquityComparablesResponse = Message<"civil.public.parcels.v1.GetEquityComparablesResponse"> & {
  /**
   * @generated from field: map<string, civil.public.parcels.v1.EquityComparableParcel> parcels = 1;
   */
  parcels: { [key: string]: EquityComparableParcel };
};

/**
 * Describes the message civil.public.parcels.v1.GetEquityComparablesResponse.
 * Use `create(GetEquityComparablesResponseSchema)` to create a new message.
 */
export declare const GetEquityComparablesResponseSchema: GenMessage<GetEquityComparablesResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetSalesComparablesRequest
 */
export declare type GetSalesComparablesRequest = Message<"civil.public.parcels.v1.GetSalesComparablesRequest"> & {
  /**
   * @generated from field: string wkt_polygon = 1;
   */
  wktPolygon: string;

  /**
   * @generated from field: repeated civil.public.parcels.v1.ComparableCriteria criteria = 2;
   */
  criteria: ComparableCriteria[];

  /**
   * @generated from field: repeated string selected_parcel_ids = 3;
   */
  selectedParcelIds: string[];

  /**
   * @generated from field: google.type.Interval time_range = 4;
   */
  timeRange?: Interval;
};

/**
 * Describes the message civil.public.parcels.v1.GetSalesComparablesRequest.
 * Use `create(GetSalesComparablesRequestSchema)` to create a new message.
 */
export declare const GetSalesComparablesRequestSchema: GenMessage<GetSalesComparablesRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetSalesComparablesResponse
 */
export declare type GetSalesComparablesResponse = Message<"civil.public.parcels.v1.GetSalesComparablesResponse"> & {
  /**
   * @generated from field: map<string, civil.public.parcels.v1.SaleComparableParcel> parcels = 1;
   */
  parcels: { [key: string]: SaleComparableParcel };
};

/**
 * Describes the message civil.public.parcels.v1.GetSalesComparablesResponse.
 * Use `create(GetSalesComparablesResponseSchema)` to create a new message.
 */
export declare const GetSalesComparablesResponseSchema: GenMessage<GetSalesComparablesResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelIdsByFeatureIdRequest
 */
export declare type GetParcelIdsByFeatureIdRequest = Message<"civil.public.parcels.v1.GetParcelIdsByFeatureIdRequest"> & {
  /**
   * @generated from field: repeated int64 feature_ids = 1;
   */
  featureIds: bigint[];
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelIdsByFeatureIdRequest.
 * Use `create(GetParcelIdsByFeatureIdRequestSchema)` to create a new message.
 */
export declare const GetParcelIdsByFeatureIdRequestSchema: GenMessage<GetParcelIdsByFeatureIdRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelIdsByFeatureIdResponse
 */
export declare type GetParcelIdsByFeatureIdResponse = Message<"civil.public.parcels.v1.GetParcelIdsByFeatureIdResponse"> & {
  /**
   * @generated from field: map<int64, string> parcel_ids = 1;
   */
  parcelIds: { [key: string]: string };
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelIdsByFeatureIdResponse.
 * Use `create(GetParcelIdsByFeatureIdResponseSchema)` to create a new message.
 */
export declare const GetParcelIdsByFeatureIdResponseSchema: GenMessage<GetParcelIdsByFeatureIdResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetEstimatedParcelsExtentWGS84Request
 */
export declare type GetEstimatedParcelsExtentWGS84Request = Message<"civil.public.parcels.v1.GetEstimatedParcelsExtentWGS84Request"> & {
};

/**
 * Describes the message civil.public.parcels.v1.GetEstimatedParcelsExtentWGS84Request.
 * Use `create(GetEstimatedParcelsExtentWGS84RequestSchema)` to create a new message.
 */
export declare const GetEstimatedParcelsExtentWGS84RequestSchema: GenMessage<GetEstimatedParcelsExtentWGS84Request>;

/**
 * @generated from message civil.public.parcels.v1.GetEstimatedParcelsExtentWGS84Response
 */
export declare type GetEstimatedParcelsExtentWGS84Response = Message<"civil.public.parcels.v1.GetEstimatedParcelsExtentWGS84Response"> & {
  /**
   * @generated from field: double min_x = 1;
   */
  minX: number;

  /**
   * @generated from field: double min_y = 2;
   */
  minY: number;

  /**
   * @generated from field: double max_x = 3;
   */
  maxX: number;

  /**
   * @generated from field: double max_y = 4;
   */
  maxY: number;
};

/**
 * Describes the message civil.public.parcels.v1.GetEstimatedParcelsExtentWGS84Response.
 * Use `create(GetEstimatedParcelsExtentWGS84ResponseSchema)` to create a new message.
 */
export declare const GetEstimatedParcelsExtentWGS84ResponseSchema: GenMessage<GetEstimatedParcelsExtentWGS84Response>;

/**
 * @generated from enum civil.public.parcels.v1.ParcelAttribute
 */
export enum ParcelAttribute {
  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_LAND_AREA_SQ_FT = 1;
   */
  LAND_AREA_SQ_FT = 1,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_FRONTAGE_FT = 2;
   */
  FRONTAGE_FT = 2,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_DEPTH_FT = 3;
   */
  DEPTH_FT = 3,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_LAND_USE_ID = 4;
   */
  LAND_USE_ID = 4,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_ZONING_ID = 5;
   */
  ZONING_ID = 5,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_IMPROVEMENT_AREA_SQ_FT = 6;
   */
  IMPROVEMENT_AREA_SQ_FT = 6,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_IMPROVEMENT_YEAR_BUILT = 7;
   */
  IMPROVEMENT_YEAR_BUILT = 7,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_IMPROVEMENT_EFFECTIVE_YEAR_BUILT = 8;
   */
  IMPROVEMENT_EFFECTIVE_YEAR_BUILT = 8,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_BEDROOMS = 9;
   */
  BEDROOMS = 9,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_BATHROOMS = 10;
   */
  BATHROOMS = 10,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_UNITS = 11;
   */
  UNITS = 11,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_CONDITION_ID = 12;
   */
  CONDITION_ID = 12,

  /**
   * @generated from enum value: PARCEL_ATTRIBUTE_IMPROVEMENT_TYPE_ID = 13;
   */
  IMPROVEMENT_TYPE_ID = 13,
}

/**
 * Describes the enum civil.public.parcels.v1.ParcelAttribute.
 */
export declare const ParcelAttributeSchema: GenEnum<ParcelAttribute>;

/**
 * @generated from service civil.public.parcels.v1.ParcelsService
 */
export declare const ParcelsService: GenService<{
  /**
   * Retrieves all of a specified parcel's attributes as an object.
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetParcelsWithImprovementSummaryByParcelId
   */
  getParcelsWithImprovementSummaryByParcelId: {
    methodKind: "unary";
    input: typeof GetParcelsWithImprovementSummaryByParcelIdRequestSchema;
    output: typeof GetParcelsWithImprovementSummaryByParcelIdResponseSchema;
  },
  /**
   * @generated from rpc civil.public.parcels.v1.ParcelsService.UpdateParcel
   */
  updateParcel: {
    methodKind: "unary";
    input: typeof UpdateParcelRequestSchema;
    output: typeof UpdateParcelResponseSchema;
  },
  /**
   * Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetNumericalParcelAttributeStatsById
   */
  getNumericalParcelAttributeStatsById: {
    methodKind: "unary";
    input: typeof GetNumericalParcelAttributeStatsByIdRequestSchema;
    output: typeof GetNumericalParcelAttributeStatsByIdResponseSchema;
  },
  /**
   * Retrieves a set of summary statistics about the specified categorical attribute for a specified list of parcels. Optionally returns the values as well
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetCategoricalParcelAttributeStatsById
   */
  getCategoricalParcelAttributeStatsById: {
    methodKind: "unary";
    input: typeof GetCategoricalParcelAttributeStatsByIdRequestSchema;
    output: typeof GetCategoricalParcelAttributeStatsByIdResponseSchema;
  },
  /**
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetEquityComparables
   */
  getEquityComparables: {
    methodKind: "unary";
    input: typeof GetEquityComparablesRequestSchema;
    output: typeof GetEquityComparablesResponseSchema;
  },
  /**
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetSalesComparables
   */
  getSalesComparables: {
    methodKind: "unary";
    input: typeof GetSalesComparablesRequestSchema;
    output: typeof GetSalesComparablesResponseSchema;
  },
  /**
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetParcelsWithImprovementSummaryByFeatureId
   */
  getParcelsWithImprovementSummaryByFeatureId: {
    methodKind: "unary";
    input: typeof GetParcelsWithImprovementSummaryByFeatureIdRequestSchema;
    output: typeof GetParcelsWithImprovementSummaryByFeatureIdResponseSchema;
  },
  /**
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetParcelIdsByFeatureId
   */
  getParcelIdsByFeatureId: {
    methodKind: "unary";
    input: typeof GetParcelIdsByFeatureIdRequestSchema;
    output: typeof GetParcelIdsByFeatureIdResponseSchema;
  },
  /**
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetEstimatedParcelsExtentWGS84
   */
  getEstimatedParcelsExtentWGS84: {
    methodKind: "unary";
    input: typeof GetEstimatedParcelsExtentWGS84RequestSchema;
    output: typeof GetEstimatedParcelsExtentWGS84ResponseSchema;
  },
}>;

