// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/parcels/v1/parcels.proto (package civil.public.parcels.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file civil/public/parcels/v1/parcels.proto.
 */
export declare const file_civil_public_parcels_v1_parcels: GenFile;

/**
 * @generated from message civil.public.parcels.v1.ParcelAffordances
 */
export declare type ParcelAffordances = Message<"civil.public.parcels.v1.ParcelAffordances"> & {
  /**
   * Maximum Floor Area Ratio (FAR)
   *
   * @generated from field: optional double max_far = 1;
   */
  maxFar?: number;

  /**
   * Minimum lot size in square feet
   *
   * @generated from field: optional double min_lot_size_sq_ft = 2;
   */
  minLotSizeSqFt?: number;

  /**
   * Maximum legally permitted building height in feet
   *
   * @generated from field: optional double max_height_ft = 3;
   */
  maxHeightFt?: number;
};

/**
 * Describes the message civil.public.parcels.v1.ParcelAffordances.
 * Use `create(ParcelAffordancesSchema)` to create a new message.
 */
export declare const ParcelAffordancesSchema: GenMessage<ParcelAffordances>;

/**
 * @generated from message civil.public.parcels.v1.ParcelImprovementsSummary
 */
export declare type ParcelImprovementsSummary = Message<"civil.public.parcels.v1.ParcelImprovementsSummary"> & {
  /**
   * @generated from field: repeated string improvement_ids = 1;
   */
  improvementIds: string[];

  /**
   * Additives: Physically impossible to be negative
   *
   * @generated from field: optional double total_area_sq_ft = 2;
   */
  totalAreaSqFt?: number;

  /**
   * @generated from field: optional int32 total_bathrooms = 3;
   */
  totalBathrooms?: number;

  /**
   * @generated from field: optional int32 total_bedrooms = 4;
   */
  totalBedrooms?: number;

  /**
   * @generated from field: optional int32 total_units = 5;
   */
  totalUnits?: number;

  /**
   * Temporals: Bounded to realistic historical/future parameters
   *
   * @generated from field: optional int32 oldest_year_built = 6;
   */
  oldestYearBuilt?: number;

  /**
   * @generated from field: optional int32 newest_year_built = 7;
   */
  newestYearBuilt?: number;

  /**
   * Qualitatives: Bounded to Civil's specific property condition ordinal scale
   *
   * @generated from field: optional int32 lowest_condition_num = 8;
   */
  lowestConditionNum?: number;

  /**
   * @generated from field: optional int32 highest_condition_num = 9;
   */
  highestConditionNum?: number;
};

/**
 * Describes the message civil.public.parcels.v1.ParcelImprovementsSummary.
 * Use `create(ParcelImprovementsSummarySchema)` to create a new message.
 */
export declare const ParcelImprovementsSummarySchema: GenMessage<ParcelImprovementsSummary>;

/**
 * @generated from message civil.public.parcels.v1.Parcel
 */
export declare type Parcel = Message<"civil.public.parcels.v1.Parcel"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;

  /**
   * @generated from field: string address = 2;
   */
  address: string;

  /**
   * @generated from field: string address_id = 3;
   */
  addressId: string;

  /**
   * @generated from field: string owner_name = 4;
   */
  ownerName: string;

  /**
   * @generated from field: string owner_address = 5;
   */
  ownerAddress: string;

  /**
   * @generated from field: string owner_id = 6;
   */
  ownerId: string;

  /**
   * @generated from field: double land_area_sq_ft = 7;
   */
  landAreaSqFt: number;

  /**
   * @generated from field: string land_use = 8;
   */
  landUse: string;

  /**
   * @generated from field: optional string land_use_code = 9;
   */
  landUseCode?: string;

  /**
   * @generated from field: optional string neighborhood = 10;
   */
  neighborhood?: string;

  /**
   * @generated from field: optional string market_area = 11;
   */
  marketArea?: string;

  /**
   * @generated from field: repeated string zoning = 12;
   */
  zoning: string[];

  /**
   * @generated from field: repeated string zoning_codes = 13;
   */
  zoningCodes: string[];

  /**
   * @generated from field: string market_land_value = 14;
   */
  marketLandValue: string;

  /**
   * @generated from field: string assessed_land_value = 15;
   */
  assessedLandValue: string;

  /**
   * @generated from field: string market_improvement_value = 16;
   */
  marketImprovementValue: string;

  /**
   * @generated from field: string assessed_improvement_value = 17;
   */
  assessedImprovementValue: string;

  /**
   * @generated from field: civil.public.parcels.v1.ParcelAffordances affordances = 18;
   */
  affordances?: ParcelAffordances;

  /**
   * @generated from field: civil.public.parcels.v1.ParcelImprovementsSummary improvement_summary = 19;
   */
  improvementSummary?: ParcelImprovementsSummary;

  /**
   * @generated from field: string properties = 20;
   */
  properties: string;
};

/**
 * Describes the message civil.public.parcels.v1.Parcel.
 * Use `create(ParcelSchema)` to create a new message.
 */
export declare const ParcelSchema: GenMessage<Parcel>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelsByIdRequest
 */
export declare type GetParcelsByIdRequest = Message<"civil.public.parcels.v1.GetParcelsByIdRequest"> & {
  /**
   * @generated from field: repeated string parcel_ids = 1;
   */
  parcelIds: string[];

  /**
   * The historical or future effective date the user wants to view.
   * If omitted, defaults to the current time.
   *
   * @generated from field: optional google.protobuf.Timestamp legal_as_of = 2;
   */
  legalAsOf?: Timestamp;

  /**
   * The time to reset the database state to
   * If omitted, defaults to the current time.
   *
   * @generated from field: optional google.protobuf.Timestamp system_as_of = 3;
   */
  systemAsOf?: Timestamp;
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelsByIdRequest.
 * Use `create(GetParcelsByIdRequestSchema)` to create a new message.
 */
export declare const GetParcelsByIdRequestSchema: GenMessage<GetParcelsByIdRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelsByIdResponse
 */
export declare type GetParcelsByIdResponse = Message<"civil.public.parcels.v1.GetParcelsByIdResponse"> & {
  /**
   * A map of parcel records, keyed by their public ID.
   *
   * @generated from field: map<string, civil.public.parcels.v1.Parcel> parcels = 1;
   */
  parcels: { [key: string]: Parcel };
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelsByIdResponse.
 * Use `create(GetParcelsByIdResponseSchema)` to create a new message.
 */
export declare const GetParcelsByIdResponseSchema: GenMessage<GetParcelsByIdResponse>;

/**
 * @generated from message civil.public.parcels.v1.UpdateParcelRequest
 */
export declare type UpdateParcelRequest = Message<"civil.public.parcels.v1.UpdateParcelRequest"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;

  /**
   * @generated from field: optional double land_area_sq_ft = 2;
   */
  landAreaSqFt?: number;

  /**
   * @generated from field: string market_land_value = 3;
   */
  marketLandValue: string;

  /**
   * @generated from field: string assessed_land_value = 4;
   */
  assessedLandValue: string;

  /**
   * @generated from field: optional string address_id = 5;
   */
  addressId?: string;

  /**
   * @generated from field: optional string owner_id = 6;
   */
  ownerId?: string;

  /**
   * @generated from field: optional string land_use_id = 7;
   */
  landUseId?: string;

  /**
   * @generated from field: optional string neighborhood_id = 8;
   */
  neighborhoodId?: string;

  /**
   * @generated from field: optional string market_area_id = 9;
   */
  marketAreaId?: string;
};

/**
 * Describes the message civil.public.parcels.v1.UpdateParcelRequest.
 * Use `create(UpdateParcelRequestSchema)` to create a new message.
 */
export declare const UpdateParcelRequestSchema: GenMessage<UpdateParcelRequest>;

/**
 * @generated from message civil.public.parcels.v1.UpdateParcelResponse
 */
export declare type UpdateParcelResponse = Message<"civil.public.parcels.v1.UpdateParcelResponse"> & {
};

/**
 * Describes the message civil.public.parcels.v1.UpdateParcelResponse.
 * Use `create(UpdateParcelResponseSchema)` to create a new message.
 */
export declare const UpdateParcelResponseSchema: GenMessage<UpdateParcelResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetNumericalParcelStatsByIdRequest
 */
export declare type GetNumericalParcelStatsByIdRequest = Message<"civil.public.parcels.v1.GetNumericalParcelStatsByIdRequest"> & {
  /**
   * @generated from field: repeated string parcel_ids = 1;
   */
  parcelIds: string[];

  /**
   * @generated from field: string attribute_name = 2;
   */
  attributeName: string;

  /**
   * @generated from field: bool return_values = 3;
   */
  returnValues: boolean;
};

/**
 * Describes the message civil.public.parcels.v1.GetNumericalParcelStatsByIdRequest.
 * Use `create(GetNumericalParcelStatsByIdRequestSchema)` to create a new message.
 */
export declare const GetNumericalParcelStatsByIdRequestSchema: GenMessage<GetNumericalParcelStatsByIdRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetNumericalParcelStatsByIdResponse
 */
export declare type GetNumericalParcelStatsByIdResponse = Message<"civil.public.parcels.v1.GetNumericalParcelStatsByIdResponse"> & {
  /**
   * @generated from field: float mode = 1;
   */
  mode: number;

  /**
   * @generated from field: float minimum = 2;
   */
  minimum: number;

  /**
   * @generated from field: float maximum = 3;
   */
  maximum: number;

  /**
   * @generated from field: float range = 4;
   */
  range: number;

  /**
   * @generated from field: float percentile_10 = 5;
   */
  percentile10: number;

  /**
   * @generated from field: float percentile_20 = 6;
   */
  percentile20: number;

  /**
   * @generated from field: float percentile_30 = 7;
   */
  percentile30: number;

  /**
   * @generated from field: float percentile_40 = 8;
   */
  percentile40: number;

  /**
   * @generated from field: float percentile_50 = 9;
   */
  percentile50: number;

  /**
   * @generated from field: float percentile_60 = 10;
   */
  percentile60: number;

  /**
   * @generated from field: float percentile_70 = 11;
   */
  percentile70: number;

  /**
   * @generated from field: float percentile_80 = 12;
   */
  percentile80: number;

  /**
   * @generated from field: float percentile_90 = 13;
   */
  percentile90: number;

  /**
   * @generated from field: float percentile_100 = 14;
   */
  percentile100: number;

  /**
   * @generated from field: float mean = 15;
   */
  mean: number;

  /**
   * @generated from field: float standard_deviation = 16;
   */
  standardDeviation: number;

  /**
   * @generated from field: float coefficient_of_dispersion = 17;
   */
  coefficientOfDispersion: number;
};

/**
 * Describes the message civil.public.parcels.v1.GetNumericalParcelStatsByIdResponse.
 * Use `create(GetNumericalParcelStatsByIdResponseSchema)` to create a new message.
 */
export declare const GetNumericalParcelStatsByIdResponseSchema: GenMessage<GetNumericalParcelStatsByIdResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetCategoricalParcelStatsByIdRequest
 */
export declare type GetCategoricalParcelStatsByIdRequest = Message<"civil.public.parcels.v1.GetCategoricalParcelStatsByIdRequest"> & {
  /**
   * @generated from field: repeated string parcel_ids = 1;
   */
  parcelIds: string[];

  /**
   * @generated from field: string attribute_name = 2;
   */
  attributeName: string;

  /**
   * @generated from field: bool return_values = 3;
   */
  returnValues: boolean;
};

/**
 * Describes the message civil.public.parcels.v1.GetCategoricalParcelStatsByIdRequest.
 * Use `create(GetCategoricalParcelStatsByIdRequestSchema)` to create a new message.
 */
export declare const GetCategoricalParcelStatsByIdRequestSchema: GenMessage<GetCategoricalParcelStatsByIdRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetCategoricalParcelStatsByIdResponse
 */
export declare type GetCategoricalParcelStatsByIdResponse = Message<"civil.public.parcels.v1.GetCategoricalParcelStatsByIdResponse"> & {
  /**
   * @generated from field: string mode = 1;
   */
  mode: string;

  /**
   * @generated from field: map<string, int32> unique_values = 2;
   */
  uniqueValues: { [key: string]: number };
};

/**
 * Describes the message civil.public.parcels.v1.GetCategoricalParcelStatsByIdResponse.
 * Use `create(GetCategoricalParcelStatsByIdResponseSchema)` to create a new message.
 */
export declare const GetCategoricalParcelStatsByIdResponseSchema: GenMessage<GetCategoricalParcelStatsByIdResponse>;

/**
 * @generated from service civil.public.parcels.v1.ParcelsService
 */
export declare const ParcelsService: GenService<{
  /**
   * Retrieves all of a specified parcel's attributes as an object.
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetParcelsById
   */
  getParcelsById: {
    methodKind: "unary";
    input: typeof GetParcelsByIdRequestSchema;
    output: typeof GetParcelsByIdResponseSchema;
  },
  /**
   * @generated from rpc civil.public.parcels.v1.ParcelsService.UpdateParcel
   */
  updateParcel: {
    methodKind: "unary";
    input: typeof UpdateParcelRequestSchema;
    output: typeof UpdateParcelResponseSchema;
  },
  /**
   * Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetNumericalParcelStatsById
   */
  getNumericalParcelStatsById: {
    methodKind: "unary";
    input: typeof GetNumericalParcelStatsByIdRequestSchema;
    output: typeof GetNumericalParcelStatsByIdResponseSchema;
  },
  /**
   * Retrieves a set of summary statistics about the specified categorical attribute for a specified list of parcels. Optionally returns the values as well
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetCategoricalParcelStatsById
   */
  getCategoricalParcelStatsById: {
    methodKind: "unary";
    input: typeof GetCategoricalParcelStatsByIdRequestSchema;
    output: typeof GetCategoricalParcelStatsByIdResponseSchema;
  },
}>;

