// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/parcels/v1/parcels.proto (package civil.public.parcels.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file civil/public/parcels/v1/parcels.proto.
 */
export declare const file_civil_public_parcels_v1_parcels: GenFile;

/**
 * @generated from message civil.public.parcels.v1.UpdateParcelsAttributeRequest
 */
export declare type UpdateParcelsAttributeRequest = Message<"civil.public.parcels.v1.UpdateParcelsAttributeRequest"> & {
  /**
   * @generated from field: repeated string parcel_ids = 1;
   */
  parcelIds: string[];

  /**
   * @generated from field: string attribute_name = 2;
   */
  attributeName: string;

  /**
   * @generated from field: string attribute_value = 3;
   */
  attributeValue: string;
};

/**
 * Describes the message civil.public.parcels.v1.UpdateParcelsAttributeRequest.
 * Use `create(UpdateParcelsAttributeRequestSchema)` to create a new message.
 */
export declare const UpdateParcelsAttributeRequestSchema: GenMessage<UpdateParcelsAttributeRequest>;

/**
 * @generated from message civil.public.parcels.v1.UpdateParcelsAttributeResponse
 */
export declare type UpdateParcelsAttributeResponse = Message<"civil.public.parcels.v1.UpdateParcelsAttributeResponse"> & {
};

/**
 * Describes the message civil.public.parcels.v1.UpdateParcelsAttributeResponse.
 * Use `create(UpdateParcelsAttributeResponseSchema)` to create a new message.
 */
export declare const UpdateParcelsAttributeResponseSchema: GenMessage<UpdateParcelsAttributeResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelRequest
 */
export declare type GetParcelRequest = Message<"civil.public.parcels.v1.GetParcelRequest"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelRequest.
 * Use `create(GetParcelRequestSchema)` to create a new message.
 */
export declare const GetParcelRequestSchema: GenMessage<GetParcelRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelResponse
 */
export declare type GetParcelResponse = Message<"civil.public.parcels.v1.GetParcelResponse"> & {
  /**
   * @generated from field: google.protobuf.Struct parcel_attributes = 1;
   */
  parcelAttributes?: JsonObject;
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelResponse.
 * Use `create(GetParcelResponseSchema)` to create a new message.
 */
export declare const GetParcelResponseSchema: GenMessage<GetParcelResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelAttributeRequest
 */
export declare type GetParcelAttributeRequest = Message<"civil.public.parcels.v1.GetParcelAttributeRequest"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;

  /**
   * @generated from field: string attribute_name = 2;
   */
  attributeName: string;
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelAttributeRequest.
 * Use `create(GetParcelAttributeRequestSchema)` to create a new message.
 */
export declare const GetParcelAttributeRequestSchema: GenMessage<GetParcelAttributeRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelAttributeResponse
 */
export declare type GetParcelAttributeResponse = Message<"civil.public.parcels.v1.GetParcelAttributeResponse"> & {
  /**
   * @generated from field: string attribute_value = 3;
   */
  attributeValue: string;
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelAttributeResponse.
 * Use `create(GetParcelAttributeResponseSchema)` to create a new message.
 */
export declare const GetParcelAttributeResponseSchema: GenMessage<GetParcelAttributeResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelAttributesRequest
 */
export declare type GetParcelAttributesRequest = Message<"civil.public.parcels.v1.GetParcelAttributesRequest"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;

  /**
   * @generated from field: repeated string attribute_names = 2;
   */
  attributeNames: string[];
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelAttributesRequest.
 * Use `create(GetParcelAttributesRequestSchema)` to create a new message.
 */
export declare const GetParcelAttributesRequestSchema: GenMessage<GetParcelAttributesRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetParcelAttributesResponse
 */
export declare type GetParcelAttributesResponse = Message<"civil.public.parcels.v1.GetParcelAttributesResponse"> & {
  /**
   * @generated from field: google.protobuf.Struct parcel_attributes = 1;
   */
  parcelAttributes?: JsonObject;
};

/**
 * Describes the message civil.public.parcels.v1.GetParcelAttributesResponse.
 * Use `create(GetParcelAttributesResponseSchema)` to create a new message.
 */
export declare const GetParcelAttributesResponseSchema: GenMessage<GetParcelAttributesResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetNumericalStatsRequest
 */
export declare type GetNumericalStatsRequest = Message<"civil.public.parcels.v1.GetNumericalStatsRequest"> & {
  /**
   * @generated from field: repeated string parcel_ids = 1;
   */
  parcelIds: string[];

  /**
   * @generated from field: string attribute_name = 2;
   */
  attributeName: string;

  /**
   * @generated from field: bool return_values = 3;
   */
  returnValues: boolean;
};

/**
 * Describes the message civil.public.parcels.v1.GetNumericalStatsRequest.
 * Use `create(GetNumericalStatsRequestSchema)` to create a new message.
 */
export declare const GetNumericalStatsRequestSchema: GenMessage<GetNumericalStatsRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetNumericalStatsResponse
 */
export declare type GetNumericalStatsResponse = Message<"civil.public.parcels.v1.GetNumericalStatsResponse"> & {
  /**
   * @generated from field: float mode = 1;
   */
  mode: number;

  /**
   * @generated from field: float minimum = 2;
   */
  minimum: number;

  /**
   * @generated from field: float maximum = 3;
   */
  maximum: number;

  /**
   * @generated from field: float range = 4;
   */
  range: number;

  /**
   * @generated from field: float percentile_10 = 5;
   */
  percentile10: number;

  /**
   * @generated from field: float percentile_20 = 6;
   */
  percentile20: number;

  /**
   * @generated from field: float percentile_30 = 7;
   */
  percentile30: number;

  /**
   * @generated from field: float percentile_40 = 8;
   */
  percentile40: number;

  /**
   * @generated from field: float percentile_50 = 9;
   */
  percentile50: number;

  /**
   * @generated from field: float percentile_60 = 10;
   */
  percentile60: number;

  /**
   * @generated from field: float percentile_70 = 11;
   */
  percentile70: number;

  /**
   * @generated from field: float percentile_80 = 12;
   */
  percentile80: number;

  /**
   * @generated from field: float percentile_90 = 13;
   */
  percentile90: number;

  /**
   * @generated from field: float percentile_100 = 14;
   */
  percentile100: number;

  /**
   * @generated from field: float mean = 15;
   */
  mean: number;

  /**
   * @generated from field: float standard_deviation = 16;
   */
  standardDeviation: number;

  /**
   * @generated from field: float coefficient_of_dispersion = 17;
   */
  coefficientOfDispersion: number;
};

/**
 * Describes the message civil.public.parcels.v1.GetNumericalStatsResponse.
 * Use `create(GetNumericalStatsResponseSchema)` to create a new message.
 */
export declare const GetNumericalStatsResponseSchema: GenMessage<GetNumericalStatsResponse>;

/**
 * @generated from message civil.public.parcels.v1.GetCategoricalStatsRequest
 */
export declare type GetCategoricalStatsRequest = Message<"civil.public.parcels.v1.GetCategoricalStatsRequest"> & {
  /**
   * @generated from field: repeated string parcel_ids = 1;
   */
  parcelIds: string[];

  /**
   * @generated from field: string attribute_name = 2;
   */
  attributeName: string;

  /**
   * @generated from field: bool return_values = 3;
   */
  returnValues: boolean;
};

/**
 * Describes the message civil.public.parcels.v1.GetCategoricalStatsRequest.
 * Use `create(GetCategoricalStatsRequestSchema)` to create a new message.
 */
export declare const GetCategoricalStatsRequestSchema: GenMessage<GetCategoricalStatsRequest>;

/**
 * @generated from message civil.public.parcels.v1.GetCategoricalStatsResponse
 */
export declare type GetCategoricalStatsResponse = Message<"civil.public.parcels.v1.GetCategoricalStatsResponse"> & {
  /**
   * @generated from field: string mode = 1;
   */
  mode: string;

  /**
   * @generated from field: map<string, int32> unique_values = 2;
   */
  uniqueValues: { [key: string]: number };
};

/**
 * Describes the message civil.public.parcels.v1.GetCategoricalStatsResponse.
 * Use `create(GetCategoricalStatsResponseSchema)` to create a new message.
 */
export declare const GetCategoricalStatsResponseSchema: GenMessage<GetCategoricalStatsResponse>;

/**
 * @generated from service civil.public.parcels.v1.ParcelsService
 */
export declare const ParcelsService: GenService<{
  /**
   * Updates a specified attribute for one or more parcels, identified by their parcel IDs.
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.UpdateParcelsAttribute
   */
  updateParcelsAttribute: {
    methodKind: "unary";
    input: typeof UpdateParcelsAttributeRequestSchema;
    output: typeof UpdateParcelsAttributeResponseSchema;
  },
  /**
   * Retrieves all of a specified parcel's attributes as an object.
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetParcel
   */
  getParcel: {
    methodKind: "unary";
    input: typeof GetParcelRequestSchema;
    output: typeof GetParcelResponseSchema;
  },
  /**
   * Retrieves a specified attribute value for a given parcel.
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetParcelAttribute
   */
  getParcelAttribute: {
    methodKind: "unary";
    input: typeof GetParcelAttributeRequestSchema;
    output: typeof GetParcelAttributeResponseSchema;
  },
  /**
   * Retrieves specificied attributes about a parcel as an object.
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetParcelAttributes
   */
  getParcelAttributes: {
    methodKind: "unary";
    input: typeof GetParcelAttributesRequestSchema;
    output: typeof GetParcelAttributesResponseSchema;
  },
  /**
   * Retrieves a set of summary statistics about the specified numerical attribute for a specified list of parcels. Optionally returns the values as well
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetNumericalStats
   */
  getNumericalStats: {
    methodKind: "unary";
    input: typeof GetNumericalStatsRequestSchema;
    output: typeof GetNumericalStatsResponseSchema;
  },
  /**
   * Retrieves a set of summary statistics about the specified categorical attribute for a specified list of parcels. Optionally returns the values as well
   *
   * @generated from rpc civil.public.parcels.v1.ParcelsService.GetCategoricalStats
   */
  getCategoricalStats: {
    methodKind: "unary";
    input: typeof GetCategoricalStatsRequestSchema;
    output: typeof GetCategoricalStatsResponseSchema;
  },
}>;

