// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/neighborhoods/v1/neighborhoods.proto (package civil.public.neighborhoods.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file civil/public/neighborhoods/v1/neighborhoods.proto.
 */
export declare const file_civil_public_neighborhoods_v1_neighborhoods: GenFile;

/**
 * @generated from message civil.public.neighborhoods.v1.NeighborhoodDefinition
 */
export declare type NeighborhoodDefinition = Message<"civil.public.neighborhoods.v1.NeighborhoodDefinition"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: bool is_legal = 3;
   */
  isLegal: boolean;
};

/**
 * Describes the message civil.public.neighborhoods.v1.NeighborhoodDefinition.
 * Use `create(NeighborhoodDefinitionSchema)` to create a new message.
 */
export declare const NeighborhoodDefinitionSchema: GenMessage<NeighborhoodDefinition>;

/**
 * @generated from message civil.public.neighborhoods.v1.Neighborhood
 */
export declare type Neighborhood = Message<"civil.public.neighborhoods.v1.Neighborhood"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message civil.public.neighborhoods.v1.Neighborhood.
 * Use `create(NeighborhoodSchema)` to create a new message.
 */
export declare const NeighborhoodSchema: GenMessage<Neighborhood>;

/**
 * @generated from message civil.public.neighborhoods.v1.GetNeighborhoodDefinitionsRequest
 */
export declare type GetNeighborhoodDefinitionsRequest = Message<"civil.public.neighborhoods.v1.GetNeighborhoodDefinitionsRequest"> & {
};

/**
 * Describes the message civil.public.neighborhoods.v1.GetNeighborhoodDefinitionsRequest.
 * Use `create(GetNeighborhoodDefinitionsRequestSchema)` to create a new message.
 */
export declare const GetNeighborhoodDefinitionsRequestSchema: GenMessage<GetNeighborhoodDefinitionsRequest>;

/**
 * @generated from message civil.public.neighborhoods.v1.GetNeighborhoodDefinitionsResponse
 */
export declare type GetNeighborhoodDefinitionsResponse = Message<"civil.public.neighborhoods.v1.GetNeighborhoodDefinitionsResponse"> & {
  /**
   * @generated from field: map<string, civil.public.neighborhoods.v1.Neighborhood> neighborhoods = 1;
   */
  neighborhoods: { [key: string]: Neighborhood };
};

/**
 * Describes the message civil.public.neighborhoods.v1.GetNeighborhoodDefinitionsResponse.
 * Use `create(GetNeighborhoodDefinitionsResponseSchema)` to create a new message.
 */
export declare const GetNeighborhoodDefinitionsResponseSchema: GenMessage<GetNeighborhoodDefinitionsResponse>;

/**
 * @generated from message civil.public.neighborhoods.v1.GetNeighborhoodsRequest
 */
export declare type GetNeighborhoodsRequest = Message<"civil.public.neighborhoods.v1.GetNeighborhoodsRequest"> & {
};

/**
 * Describes the message civil.public.neighborhoods.v1.GetNeighborhoodsRequest.
 * Use `create(GetNeighborhoodsRequestSchema)` to create a new message.
 */
export declare const GetNeighborhoodsRequestSchema: GenMessage<GetNeighborhoodsRequest>;

/**
 * @generated from message civil.public.neighborhoods.v1.GetNeighborhoodsResponse
 */
export declare type GetNeighborhoodsResponse = Message<"civil.public.neighborhoods.v1.GetNeighborhoodsResponse"> & {
  /**
   * @generated from field: map<string, civil.public.neighborhoods.v1.Neighborhood> neighborhoods = 1;
   */
  neighborhoods: { [key: string]: Neighborhood };
};

/**
 * Describes the message civil.public.neighborhoods.v1.GetNeighborhoodsResponse.
 * Use `create(GetNeighborhoodsResponseSchema)` to create a new message.
 */
export declare const GetNeighborhoodsResponseSchema: GenMessage<GetNeighborhoodsResponse>;

/**
 * @generated from service civil.public.neighborhoods.v1.NeighborhoodService
 */
export declare const NeighborhoodService: GenService<{
  /**
   * @generated from rpc civil.public.neighborhoods.v1.NeighborhoodService.GetNeighborhoodDefinitions
   */
  getNeighborhoodDefinitions: {
    methodKind: "unary";
    input: typeof GetNeighborhoodDefinitionsRequestSchema;
    output: typeof GetNeighborhoodDefinitionsResponseSchema;
  },
  /**
   * @generated from rpc civil.public.neighborhoods.v1.NeighborhoodService.GetNeighborhoods
   */
  getNeighborhoods: {
    methodKind: "unary";
    input: typeof GetNeighborhoodsRequestSchema;
    output: typeof GetNeighborhoodsResponseSchema;
  },
}>;

