// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/public/improvements/v1/improvements.proto (package civil.public.improvements.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file civil/public/improvements/v1/improvements.proto.
 */
export declare const file_civil_public_improvements_v1_improvements: GenFile;

/**
 * @generated from message civil.public.improvements.v1.ImprovementType
 */
export declare type ImprovementType = Message<"civil.public.improvements.v1.ImprovementType"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string code = 3;
   */
  code: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;
};

/**
 * Describes the message civil.public.improvements.v1.ImprovementType.
 * Use `create(ImprovementTypeSchema)` to create a new message.
 */
export declare const ImprovementTypeSchema: GenMessage<ImprovementType>;

/**
 * @generated from message civil.public.improvements.v1.GetImprovementTypesRequest
 */
export declare type GetImprovementTypesRequest = Message<"civil.public.improvements.v1.GetImprovementTypesRequest"> & {
};

/**
 * Describes the message civil.public.improvements.v1.GetImprovementTypesRequest.
 * Use `create(GetImprovementTypesRequestSchema)` to create a new message.
 */
export declare const GetImprovementTypesRequestSchema: GenMessage<GetImprovementTypesRequest>;

/**
 * @generated from message civil.public.improvements.v1.GetImprovementTypesResponse
 */
export declare type GetImprovementTypesResponse = Message<"civil.public.improvements.v1.GetImprovementTypesResponse"> & {
  /**
   * @generated from field: map<string, civil.public.improvements.v1.ImprovementType> improvement_types = 1;
   */
  improvementTypes: { [key: string]: ImprovementType };
};

/**
 * Describes the message civil.public.improvements.v1.GetImprovementTypesResponse.
 * Use `create(GetImprovementTypesResponseSchema)` to create a new message.
 */
export declare const GetImprovementTypesResponseSchema: GenMessage<GetImprovementTypesResponse>;

/**
 * @generated from message civil.public.improvements.v1.ImprovementCondition
 */
export declare type ImprovementCondition = Message<"civil.public.improvements.v1.ImprovementCondition"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Set to optional to allow it to properly pass zero values
   *
   * @generated from field: optional float depreciation_modifier = 3;
   */
  depreciationModifier?: number;
};

/**
 * Describes the message civil.public.improvements.v1.ImprovementCondition.
 * Use `create(ImprovementConditionSchema)` to create a new message.
 */
export declare const ImprovementConditionSchema: GenMessage<ImprovementCondition>;

/**
 * @generated from message civil.public.improvements.v1.GetImprovementConditionsRequest
 */
export declare type GetImprovementConditionsRequest = Message<"civil.public.improvements.v1.GetImprovementConditionsRequest"> & {
};

/**
 * Describes the message civil.public.improvements.v1.GetImprovementConditionsRequest.
 * Use `create(GetImprovementConditionsRequestSchema)` to create a new message.
 */
export declare const GetImprovementConditionsRequestSchema: GenMessage<GetImprovementConditionsRequest>;

/**
 * @generated from message civil.public.improvements.v1.GetImprovementConditionsResponse
 */
export declare type GetImprovementConditionsResponse = Message<"civil.public.improvements.v1.GetImprovementConditionsResponse"> & {
  /**
   * @generated from field: map<string, civil.public.improvements.v1.ImprovementCondition> improvement_conditions = 1;
   */
  improvementConditions: { [key: string]: ImprovementCondition };
};

/**
 * Describes the message civil.public.improvements.v1.GetImprovementConditionsResponse.
 * Use `create(GetImprovementConditionsResponseSchema)` to create a new message.
 */
export declare const GetImprovementConditionsResponseSchema: GenMessage<GetImprovementConditionsResponse>;

/**
 * @generated from service civil.public.improvements.v1.ImprovementsService
 */
export declare const ImprovementsService: GenService<{
  /**
   * @generated from rpc civil.public.improvements.v1.ImprovementsService.GetImprovementTypes
   */
  getImprovementTypes: {
    methodKind: "unary";
    input: typeof GetImprovementTypesRequestSchema;
    output: typeof GetImprovementTypesResponseSchema;
  },
  /**
   * @generated from rpc civil.public.improvements.v1.ImprovementsService.GetImprovementConditions
   */
  getImprovementConditions: {
    methodKind: "unary";
    input: typeof GetImprovementConditionsRequestSchema;
    output: typeof GetImprovementConditionsResponseSchema;
  },
}>;

