// Copyright 2022 Google LLC. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file gnostic/openapi/v3/annotations.proto (package gnostic.openapi.v3, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv2";
import type { FieldOptions, FileOptions, MessageOptions, MethodOptions } from "@bufbuild/protobuf/wkt";
import type { Document, Operation, Schema } from "./openapiv3_pb";

/**
 * Describes the file gnostic/openapi/v3/annotations.proto.
 */
export declare const file_gnostic_openapi_v3_annotations: GenFile;

/**
 * @generated from extension: gnostic.openapi.v3.Document document = 1143;
 */
export declare const document: GenExtension<FileOptions, Document>;

/**
 * @generated from extension: gnostic.openapi.v3.Operation operation = 1143;
 */
export declare const operation: GenExtension<MethodOptions, Operation>;

/**
 * @generated from extension: gnostic.openapi.v3.Schema schema = 1143;
 */
export declare const schema: GenExtension<MessageOptions, Schema>;

/**
 * @generated from extension: gnostic.openapi.v3.Schema property = 1143;
 */
export declare const property: GenExtension<FieldOptions, Schema>;

